apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-b
  template:
    metadata:
      labels:
        app: my-app-b
      annotations:
        pod-name-prefix: "Pod B"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - my-app-b
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: my-app-b
        image: nginx:latest
        ports:
        - containerPort: 80